
server:
  port: 8080
spring:
  application:
    name: polimerlar-backend
  datasource:
    url: jdbc:postgresql://dpg-crdfbnbtq21c73d3bpj0-a.oregon-postgres.render.com/polychemphy_db
    username: polychemphy_db_user
    password: sp3wR7zzum2bjyZPdag3bdX1UL0FPxfd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      dll-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: mail.polchemphys.uz
    port: 587
    username: polchemphys
    password: polchemphys123
    properties:
            mail:
              smtp:
                auth: true
                starttls:
                  enable: true
  web:
    resources:
      static-locations: classpath:/static/

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs


app-jwt-secret: saladaf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee75500er
app-jwt-expiration-milliseconds: 7200000




